persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log

# MQTT classique
listener 1883
allow_anonymous true

# WebSocket pour interface web
listener 9001
protocol websockets
